#!/usr/bin/env ruby

require 'rubocop'

ADDED_OR_MODIFIED = /A|AM|^M/.freeze

changed_files = `git status --porcelain`.split(/\n/).
    select { |file_name_with_status|
      file_name_with_status =~ ADDED_OR_MODIFIED
     }.
    map { |file_name_with_status|
      file_name_with_status.split(' ')[1]
     }.
    select { |file_name|
      File.extname(file_name) == '.rb'
     }.join(' ')

begin
  system("bundle exec rubocop --require rubocop-rails --auto-correct --force-exclusion #{changed_files}") unless changed_files.empty?
rescue Gem::Exception
  system("rubocop --require rubocop-rails --auto-correct --force-exclusion #{changed_files}") unless changed_files.empty?
end
system("git add #{changed_files}")

exit $CHILD_STATUS.to_s[-1].to_i
